# Generated by Django 2.1 on 2018-08-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('Train_Name', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('CC_fare', models.CharField(max_length=100)),
                ('Ac3_fare', models.CharField(max_length=100)),
                ('Ac2_fare', models.CharField(max_length=100)),
                ('Ac1_fare', models.CharField(max_length=100)),
                ('Departure_time', models.CharField(max_length=100)),
                ('Arrival_time', models.CharField(max_length=10)),
                ('is_Return', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=100)),
                ('Phone_no', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=20)),
                ('Email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Log')),
            ],
        ),
    ]
