# Generated by Django 2.1 on 2018-08-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20180823_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email_id',
            field=models.CharField(max_length=100),
        ),
    ]
