# Generated by Django 2.1 on 2018-08-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20180823_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Number', models.CharField(max_length=16)),
                ('Card_Holder', models.CharField(max_length=100)),
                ('Expiry', models.CharField(max_length=20)),
                ('CVV', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_Return',
        ),
        migrations.RemoveField(
            model_name='user',
            name='CVV',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Card_Number',
        ),
    ]
